### PR TITLE
wip: support for eth-duties

### PR DESCRIPTION
**Pull request by tupakkatapa**
https://github.com/TobiWo/eth-duties

### CODE REVIEW

**Comment by jhvst** [comment]
LGTM, needs to wait for lighthouse PR which contains overlay and pkgs triggers, which links this package installable.

Can this be added to as a default package to both nodes?

**Comment by tupakkatapa** [comment]
I'm having issues with pyinstaller dependencies, specifically zlib. Additionally, the compiling process seems to be taking an abnormally long time, and I'm getting various warnings during the process. I'll try to fix this in the future, considering trying with the [`buildPythonPackage`](https://nixos.wiki/wiki/Packaging/Python) module instead of [`poetry2nix`](https://github.com/nix-community/poetry2nix).

**Comment by tupakkatapa** [comment]
This should be added directly to Nixobolus. It can be used in this repository through the 'homestakeros' module.

**Comment by jhvst** [comment]
If you make a new PR on nixobolus side and reference it here, we can close this issue here.

**Comment by tupakkatapa** [comment]
Continuing here: https://github.com/ponkila/nixobolus/pull/7

**Pull request closed without merging**
